[package]
name = "gobs-core"
version = "0.1.0"
authors = ["Daniel Parnell <me@danielparnell.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.10.1"